<?xml version="1.0"?>

<!--
License: Apache 2.0. See LICENSE file in root directory.
Copyright(c) 2017 Intel Corporation. All Rights Reserved

This is the URDF model for the Intel RealSense L515 camera, in its
aluminum peripherial evaluation case.
-->

<robot name="sensor_l515" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="sensor_l515" params="parent *origin name:=camera use_nominal_extrinsics:=false">
    <xacro:property name="M_PI" value="3.1415926535897931" />

    <!-- The following values are approximate, and the camera node
     publishing TF values with actual calibrated camera extrinsic values -->

    <!-- The following values model the aluminum peripherial case for the
  	L515 camera, with the camera joint represented by the actual
  	peripherial camera tripod mount -->
    <xacro:property name="l515_cam_width" value="0.061"/>
    <xacro:property name="l515_cam_height" value="0.06065"/>
    <xacro:property name="l515_cam_depth" value="0.026"/>
    <xacro:property name="l515_cam_mount_from_glass_offset" value="0.012"/>
    <!-- Zero depth to glass: see datasheet Revision 002, Fig. 2-2 page 11 -->
    <xacro:property name="l515_cam_depth_to_glass" value="0.0045"/>

    <!-- The following offset is relative the the physical L515 camera peripherial
  	camera tripod mount -->
    <xacro:property name="l515_cam_center" value="0.03015"/>
    <xacro:property name="l515_cam_center_to_transmitter_pz" value="0.001"/>
    <xacro:property name="l515_cam_transmitter_to_receiver_pz" value="-0.010"/>
    <xacro:property name="l515_cam_transmitter_to_rgb_pz" value="0.014"/>
    <xacro:property name="l515_cam_mount_from_center" value="0.020"/>

    <xacro:property name="l515_cam_transmitter_to_imu_py" value="-0.01245"/>
    <xacro:property name="l515_cam_transmitter_to_imu_pz" value="0.01151"/>

    <!-- camera body, with origin at bottom screw mount -->
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_bottom_screw_frame" />
    </joint>
    <link name="${name}_bottom_screw_frame"/>

    <joint name="${name}_center_joint" type="fixed">
      <origin xyz="${l515_cam_mount_from_glass_offset} 0 ${l515_cam_center}" rpy="0 0 0"/>
      <parent link="${name}_bottom_screw_frame"/>
      <child link="${name}_center_frame" />
    </joint>

    <link name="${name}_center_frame">
      <visual>
        <!-- the mesh origin is in the middle of the front plate -->
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
	        <mesh filename="package://realsense2_description/meshes/l515.dae" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="${-l515_cam_depth/2} 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
          <cylinder radius="${l515_cam_width}" length="${l515_cam_depth}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${name}_lower_mount_joint" type="fixed">
      <origin xyz="${l515_cam_mount_from_glass_offset-l515_cam_depth} 0 ${l515_cam_center-l515_cam_mount_from_center}" rpy="0 0 0" />
      <parent link="${name}_bottom_screw_frame" />
      <child link="${name}_lower_mount" />
    </joint>
    <link name="${name}_lower_mount"/>

    <joint name="${name}_upper_mount_joint" type="fixed">
      <origin xyz="${l515_cam_mount_from_glass_offset-l515_cam_depth} 0 ${l515_cam_center+l515_cam_mount_from_center}" rpy="0 0 0" />
      <parent link="${name}_bottom_screw_frame" />
      <child link="${name}_upper_mount" />
    </joint>
    <link name="${name}_upper_mount"/>

    <joint name="${name}_transmitter_joint" type="fixed">
      <origin xyz="${-l515_cam_depth_to_glass} 0 ${l515_cam_center_to_transmitter_pz}" rpy="0 0 0"/>
      <parent link="${name}_center_frame"/>
      <child link="${name}_transmitter_frame" />
    </joint>
    <link name="${name}_transmitter_frame"/>

    <joint name="${name}_receiver_joint" type="fixed">
      <origin xyz="${l515_cam_depth_to_glass} 0 ${l515_cam_transmitter_to_receiver_pz}" rpy="0 0 0"/>
      <parent link="${name}_transmitter_frame"/>
      <child link="${name}_receiver_frame" />
    </joint>
    <link name="${name}_receiver_frame"/>

    <joint name="${name}_rgb_joint" type="fixed">
      <origin xyz="${l515_cam_depth_to_glass} 0 ${l515_cam_transmitter_to_rgb_pz}" rpy="0 0 0"/>
      <parent link="${name}_transmitter_frame"/>
      <child link="${name}_rgb_frame" />
    </joint>
    <link name="${name}_rgb_frame"/>

    <joint name="${name}_imu_joint" type="fixed">
      <origin xyz = "0 ${l515_cam_transmitter_to_imu_py} ${l515_cam_transmitter_to_imu_pz}" rpy = "0 0 0" />
      <parent link="${name}_transmitter_frame" />
      <child link="${name}_imu_frame" />
    </joint>
    <link name="${name}_imu_frame" />

    <!-- Use the nominal extrinsics between camera frames if the calibrated extrinsics aren't being published. e.g. running the device in simulation  -->
    <xacro:if value="${use_nominal_extrinsics}">
      <!-- camera depth joints and links -->
      <joint name="${name}_depth_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-0.016 0.0 0.016"/>
        <parent link="${name}_transmitter_frame"/>
        <child link="${name}_depth_frame" />
      </joint>
      <link name="${name}_depth_frame"/>

      <joint name="${name}_depth_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${name}_depth_frame" />
        <child link="${name}_depth_optical_frame" />
      </joint>
      <link name="${name}_depth_optical_frame"/>

      <!-- camera IR joints and links -->
      <joint name="${name}_infra_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="${name}_receiver_frame" />
        <child link="${name}_infra_frame" />
      </joint>
      <link name="${name}_infra_frame"/>

      <joint name="${name}_infra_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${name}_infra_frame" />
        <child link="${name}_infra_optical_frame" />
      </joint>
      <link name="${name}_infra_optical_frame"/>

      <!-- camera color joints and links -->
      <joint name="${name}_color_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 -0.028 0" />
        <parent link="${name}_rgb_frame" />
        <child link="${name}_color_frame" />
      </joint>
      <link name="${name}_color_frame"/>

      <joint name="${name}_color_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${name}_color_frame" />
        <child link="${name}_color_optical_frame" />
      </joint>
      <link name="${name}_color_optical_frame"/>

      <joint name="${name}_imu_optical_joint" type="fixed">
        <origin xyz = "0 0 0" rpy = "${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${name}_imu_frame" />
        <child link="${name}_imu_optical_frame" />
      </joint>
      <link name="${name}_imu_optical_frame" />

    </xacro:if>

  </xacro:macro>
</robot>
